### ISSUE TITLE
Small UI bugs in "iletişim" page

### ISSUE THREAD

**Issue by mirkancal** [flutterturkey/turkish-dictionary#12]
<b>App Screenshot</b>

<img src=https://user-images.githubusercontent.com/26160059/77138946-0bd62680-6a85-11ea-8a66-6bbc6fea5740.png height=500>

<b>Figma File</b>

<img src=https://user-images.githubusercontent.com/26160059/77139001-48a21d80-6a85-11ea-8690-05415d19efb8.png height=500>

1) Middle text's text alignment should be center.
2) Missing tab indicator on "Katkı ve Öneriler" tab.

**Comment by mukireus** [comment]
![Screenshot_20200321-013458](https://user-images.githubusercontent.com/33984759/77211246-6cf90b00-6b14-11ea-8a12-5ae200220b2c.png)
1. Fixed
2. Bug continues
3. Iletisim and Katki tab padding bug fixed

**Comment by Adem68** [comment]
@all-contributors bot

**Comment by Adem68** [comment]
@all-contributors bot add @mirkancal @AliAnilKocak @mukireus @Adem68

**Comment by Adem68** [comment]
@all-contributors bot add @mirkancal @AliAnilKocak @mukireus @Adem68 for maintenance

**Comment by Adem68** [comment]
@all-contributors bot add @Adem68 for code and maintenance

**Comment by Adem68** [comment]
@all-contributors bot add @AliAnilKocak  for code and maintenance

**Comment by Adem68** [comment]
@all-contributors bot add @mirkancal for code and maintenance

**Comment by Adem68** [comment]
@all-contributors bot add @mirkancal for code and maintenance

**Comment by Adem68** [comment]
@all-contributors bot add @onatcipli for code and maintenance

**Comment by Adem68** [comment]
@all-contributors bot add @mukireus for code

**Comment by Adem68** [comment]
@all-contributors bot remove @mirkancal

**Comment by Adem68** [comment]
@all-contributors bot add @mukireus for code

**Comment by Adem68** [comment]
@all-contributors bot

**Comment by Adem68** [comment]
@all-contributors add @merttoptas for code

**Comment by Adem68** [comment]
@all-contributors add @right7ctrl for code
